# DANE - połączenie i przygotowanie

In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
df = pd.read_csv('../part1/data.csv')
df = df.dropna(subset=['value'])
df = df.drop(["Unnamed: 0"], axis=1)
df.columns = ['YEAR', 'MONTH', 'DAY','City','Type','Value']

In [4]:
df_w = pd.read_csv('../Data/average_daily_weather.csv')
#df = df.dropna(subset=['value'])
#df = df.drop(["Unnamed: 0"], axis=1)

In [5]:
all_data = pd.merge(df, df_w, on=['YEAR','MONTH','DAY','City'], how='inner')
all_data

YEAR  MONTH  DAY      City   Type  Value  Temperature  Wind  Humidity
0      2019      1    8  Warszawa   PM10  52.78         -2.6   3.0       8.7
1      2019      1    8  Warszawa  PM2,5  35.56         -2.6   3.0       8.7
2      2019      1    9  Warszawa   PM10  43.53         -3.1   0.0       6.8
3      2019      1    9  Warszawa  PM2,5  38.64         -3.1   0.0       6.8
4      2019      1   10  Warszawa   PM10  46.63         -6.8   2.5       8.5
...     ...    ...  ...       ...    ...    ...          ...   ...       ...
24470  2021      2   14  Katowice  PM2,5  33.20         -5.3   0.0       NaN
24471  2021      2   15  Katowice  PM2,5  59.70         -7.1   1.5       8.5
24472  2021      2   16  Katowice  PM2,5  54.90         -4.2   0.0       NaN
24473  2021      2   17  Katowice  PM2,5  33.50          1.1   3.7       9.2
24474  2021     12   26  Katowice  PM2,5  55.50         -9.3   1.5       7.8

[24475 rows x 9 columns]

In [6]:
merged_df = all_data.drop(["Humidity"], axis=1)
merged_df = merged_df.dropna()
merged_df

YEAR  MONTH  DAY      City   Type  Value  Temperature  Wind
0      2019      1    8  Warszawa   PM10  52.78         -2.6   3.0
1      2019      1    8  Warszawa  PM2,5  35.56         -2.6   3.0
2      2019      1    9  Warszawa   PM10  43.53         -3.1   0.0
3      2019      1    9  Warszawa  PM2,5  38.64         -3.1   0.0
4      2019      1   10  Warszawa   PM10  46.63         -6.8   2.5
...     ...    ...  ...       ...    ...    ...          ...   ...
24470  2021      2   14  Katowice  PM2,5  33.20         -5.3   0.0
24471  2021      2   15  Katowice  PM2,5  59.70         -7.1   1.5
24472  2021      2   16  Katowice  PM2,5  54.90         -4.2   0.0
24473  2021      2   17  Katowice  PM2,5  33.50          1.1   3.7
24474  2021     12   26  Katowice  PM2,5  55.50         -9.3   1.5

[24475 rows x 8 columns]

In [7]:
PM10 = merged_df[merged_df['Type']=='PM10']

In [8]:
# Stworzenie słownika mapującego nazwy miast na liczby całkowite
city_dict = {city: i+1 for i, city in enumerate(PM10['City'].unique())}
PM10.loc[:, 'City'] = PM10['City'].replace(city_dict)
# Zamiana nazw miast na odpowiadające im liczby całkowite
PM10

<ipython-input-8-c8f87269f0a9>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  PM10.loc[:, 'City'] = PM10['City'].replace(city_dict)
<ipython-input-8-c8f87269f0a9>:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  PM10.loc[:, 'City'] = PM10['City'].replace(city_dict)


YEAR  MONTH  DAY  City  Type  Value  Temperature  Wind
0      2019      1    8     1  PM10  52.78         -2.6   3.0
2      2019      1    9     1  PM10  43.53         -3.1   0.0
4      2019      1   10     1  PM10  46.63         -6.8   2.5
6      2019      1   11     1  PM10  53.70         -7.1   0.0
8      2019      1   12     1  PM10  25.76          0.9   2.7
...     ...    ...  ...   ...   ...    ...          ...   ...
24405  2021     12   25     5  PM10  28.00         -4.1   0.0
24407  2021     12   28     5  PM10  42.30         -4.7   2.9
24409  2021     12   29     5  PM10  45.60         -0.7   0.0
24411  2021     12   30     5  PM10  15.70          4.6   4.6
24413  2021     12   31     5  PM10  11.60          9.7   4.8

[12149 rows x 8 columns]

In [9]:
city_dict

{'Warszawa': 1, 'Wrocław': 2, 'Gdańsk': 3, 'Kraków': 4, 'Katowice': 5}

# Adding number of month

In [10]:
all_data

YEAR  MONTH  DAY      City   Type  Value  Temperature  Wind  Humidity
0      2019      1    8  Warszawa   PM10  52.78         -2.6   3.0       8.7
1      2019      1    8  Warszawa  PM2,5  35.56         -2.6   3.0       8.7
2      2019      1    9  Warszawa   PM10  43.53         -3.1   0.0       6.8
3      2019      1    9  Warszawa  PM2,5  38.64         -3.1   0.0       6.8
4      2019      1   10  Warszawa   PM10  46.63         -6.8   2.5       8.5
...     ...    ...  ...       ...    ...    ...          ...   ...       ...
24470  2021      2   14  Katowice  PM2,5  33.20         -5.3   0.0       NaN
24471  2021      2   15  Katowice  PM2,5  59.70         -7.1   1.5       8.5
24472  2021      2   16  Katowice  PM2,5  54.90         -4.2   0.0       NaN
24473  2021      2   17  Katowice  PM2,5  33.50          1.1   3.7       9.2
24474  2021     12   26  Katowice  PM2,5  55.50         -9.3   1.5       7.8

[24475 rows x 9 columns]

In [11]:
city_dict = {city: i+1 for i, city in enumerate(all_data['City'].unique())}
all_data.loc[:, 'City'] = all_data['City'].replace(city_dict)
all_data

<ipython-input-11-0c63b67166a4>:2: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  all_data.loc[:, 'City'] = all_data['City'].replace(city_dict)


YEAR  MONTH  DAY  City   Type  Value  Temperature  Wind  Humidity
0      2019      1    8     1   PM10  52.78         -2.6   3.0       8.7
1      2019      1    8     1  PM2,5  35.56         -2.6   3.0       8.7
2      2019      1    9     1   PM10  43.53         -3.1   0.0       6.8
3      2019      1    9     1  PM2,5  38.64         -3.1   0.0       6.8
4      2019      1   10     1   PM10  46.63         -6.8   2.5       8.5
...     ...    ...  ...   ...    ...    ...          ...   ...       ...
24470  2021      2   14     5  PM2,5  33.20         -5.3   0.0       NaN
24471  2021      2   15     5  PM2,5  59.70         -7.1   1.5       8.5
24472  2021      2   16     5  PM2,5  54.90         -4.2   0.0       NaN
24473  2021      2   17     5  PM2,5  33.50          1.1   3.7       9.2
24474  2021     12   26     5  PM2,5  55.50         -9.3   1.5       7.8

[24475 rows x 9 columns]

In [12]:
def two_degree(PM10_value):
    if PM10_value >= 50:
        return -1
    else:
        return 1
    
def six_degree(PM10_value):
    if PM10_value > 150:
        return -3
    elif PM10_value > 110:
        return -2
    elif PM10_value > 80:
        return -1
    elif PM10_value > 50:
        return 1
    elif PM10_value > 20:
        return 2
    else:
        return 3

In [13]:
all_data["Value_two_degree"] = all_data.Value.apply(two_degree)
all_data["Value_six_degree"] = all_data.Value.apply(six_degree)
all_data

YEAR  MONTH  DAY  City   Type  Value  Temperature  Wind  Humidity  \
0      2019      1    8     1   PM10  52.78         -2.6   3.0       8.7   
1      2019      1    8     1  PM2,5  35.56         -2.6   3.0       8.7   
2      2019      1    9     1   PM10  43.53         -3.1   0.0       6.8   
3      2019      1    9     1  PM2,5  38.64         -3.1   0.0       6.8   
4      2019      1   10     1   PM10  46.63         -6.8   2.5       8.5   
...     ...    ...  ...   ...    ...    ...          ...   ...       ...   
24470  2021      2   14     5  PM2,5  33.20         -5.3   0.0       NaN   
24471  2021      2   15     5  PM2,5  59.70         -7.1   1.5       8.5   
24472  2021      2   16     5  PM2,5  54.90         -4.2   0.0       NaN   
24473  2021      2   17     5  PM2,5  33.50          1.1   3.7       9.2   
24474  2021     12   26     5  PM2,5  55.50         -9.3   1.5       7.8   

       Value_two_degree  Value_six_degree  
0                    -1                 1  
1                     1                 2  
2                     1                 2  
3                     1                 2  
4                     1                 2  
...                 ...               ...  
24470                 1                 2  
24471                -1                 1  
24472                -1                 1  
24473                 1                 2  
24474                -1                 1  

[24475 rows x 11 columns]

In [14]:
from collections import Counter
c = Counter(all_data[all_data.Type == 'PM10'].Value_two_degree)
for v, c in c.most_common():
    print(f'{v}: {c}')


1: 10277
-1: 1872


In [15]:
from collections import Counter
c = Counter(all_data[all_data.Type == 'PM10'].Value_six_degree)
for v, c in c.most_common():
    print(f'{v}: {c}')


2: 6389
3: 3916
1: 1329
-1: 337
-2: 131
-3: 47


In [16]:
X_train = all_data[(all_data.YEAR < 2019) & (all_data.Type == 'PM10')][['MONTH', 'City', 'Temperature', 'Wind', 'YEAR']]
X_test = all_data[(all_data.YEAR == 2019) & (all_data.Type == 'PM10')][['MONTH', 'City', 'Temperature', 'Wind', 'YEAR']]
y_train = all_data[(all_data.YEAR < 2019) & (all_data.Type == 'PM10')]['Value']
y_test = all_data[(all_data.YEAR == 2019) & (all_data.Type == 'PM10')]['Value']

In [17]:
X_train

MONTH  City  Temperature  Wind  YEAR
3480       1     1          7.5   0.0  2018
3482       1     1          1.2   2.4  2018
3484       1     1          3.3   0.0  2018
3486       1     1          5.7   2.9  2018
3488       1     1          6.1   0.0  2018
...      ...   ...          ...   ...   ...
17257     12     5          8.0   0.0  2015
17259     12     5          5.5   2.2  2015
17261     12     5          1.3   0.0  2015
17263     12     5         -5.1   4.0  2015
17265     12     5         -6.8   1.2  2015

[6878 rows x 5 columns]

In [ ]:

    
    rf = RandomForestRegressor(max_depth=10, 
                               max_features='log2', 
                               n_estimators=150)



In [22]:
from sklearn.ensemble import RandomForestRegressor
from tqdm.notebook import tqdm

MC = 1000
train_stats = {'MSE':[],'MSE_sqrt':[],'MAE':[], 'MAPE':[], 'R2':[]}
test_stats = {'MSE':[],'MSE_sqrt':[],'MAE':[], 'MAPE':[],'R2':[]}

for _ in tqdm(range(MC)):
    rf = RandomForestRegressor(max_depth= 10, max_features= 'log2', n_estimators= 150)
    #rf = RandomForestRegressor(n_estimators= 150)
    rf.fit(X_train, y_train)
    
    y_predicted=rf.predict(X_test)
    test_stats['MSE'].append(mean_squared_error(y_test, y_predicted))
    test_stats['MSE_sqrt'].append(np.sqrt(test_stats['MSE'][-1]))
    test_stats['MAE'].append(mean_absolute_error(y_test, y_predicted))
    test_stats['MAPE'].append(mean_absolute_percentage_error(y_test, y_predicted))   
    test_stats['R2'].append(r2_score(y_test, y_predicted))
    
    y_predicted=rf.predict(X_train)    
    train_stats['MSE'].append(mean_squared_error(y_train, y_predicted))
    train_stats['MSE_sqrt'].append(np.sqrt(train_stats['MSE'][-1]))
    train_stats['MAE'].append(mean_absolute_error(y_train, y_predicted))
    train_stats['MAPE'].append(mean_absolute_percentage_error(y_train, y_predicted))   
    train_stats['R2'].append(r2_score(y_train, y_predicted))
   

  0%|          | 0/1000 [00:00<?, ?it/s]

In [24]:
print('Train set')
print("MSE:", np.mean(train_stats['MSE']),'  ',np.std(train_stats['MSE']))
print("MSE sqrt:", np.mean(train_stats['MSE_sqrt']),'  ',np.std(train_stats['MSE_sqrt']))
print("MAE:", np.mean(train_stats['MAE']),'  ',np.std(train_stats['MAE']))
print("MAPE:", np.mean(train_stats['MAPE']),'  ',np.std(train_stats['MAPE']))
print("R2:", np.mean(train_stats['R2']),'  ',np.std(train_stats['R2']))

print()
print('Test set')
print("MSE:", np.mean(test_stats['MSE']),'  ',np.std(test_stats['MSE']))
print("MSE sqrt:", np.mean(test_stats['MSE_sqrt']),'  ',np.std(test_stats['MSE_sqrt']))
print("MAE:", np.mean(test_stats['MAE']),'  ',np.std(test_stats['MAE']))
print("MAPE:", np.mean(test_stats['MAPE']),'  ',np.std(test_stats['MAPE']))
print("R2:", np.mean(test_stats['R2']),'  ',np.std(test_stats['R2']))

Train set
MSE: 185.2645381148672    0.9512661364031366
MSE sqrt: 13.611146798177574    0.034942142572939545
MAE: 9.248008468020974    0.017794158283499402
MAPE: 0.3348300735444509    0.0007744445770295086
R2: 0.7177989634299581    0.001448999859760002

Test set
MSE: 330.25236990703735    1.662060563671125
MSE sqrt: 18.17278951869229    0.04572763218284199
MAE: 12.817958227000288    0.029353765593291555
MAPE: 0.5032727463737491    0.0015497257775351563
R2: 0.3635041120177936    0.0032032918178659716


# Grid search

In [35]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd

# Ustawienie siatki parametrów do przeszukania
param_grid = {
    'n_estimators': [100,150,200],
    'max_depth': [10, 15, 20],
    'max_features': ['sqrt', 'log2']
}

# Inicjalizacja modelu Random Forest
rf = RandomForestRegressor()

# Ustawienie GridSearchCV z 5-fold cross validation
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)

# dopasowanie siatki parametrów
grid_search.fit(X_train, y_train)

# Uzyskanie najlepszych parametrów
best_params = grid_search.best_params_

# Utworzenie modelu z najlepszymi parametrami
rf_best = RandomForestRegressor(n_estimators=best_params['n_estimators'],
                                 max_depth=best_params['max_depth'],
                                 max_features=best_params['max_features'])

# dopasowanie modelu z najlepszymi parametrami
rf_best.fit(X_train, y_train)

# przewidywanie dla zbioru testowego
y_pred = rf_best.predict(X_test)

# obliczenie błędu średniokwadratowego
mse = mean_squared_error(y_test, y_pred)
print('Błąd średniokwadratowy:', mse)

Błąd średniokwadratowy: 330.8322524695204


In [20]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error


In [36]:
grid_search.best_params_

{'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 200}

param_grid = {
    'n_estimators': [100, 200, 500],
    'max_depth': [None, 5, 10],
    'max_features': ['sqrt', 'log2']
} 
-> 331,15 {'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 100}


param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [5, 10, 15],
    'max_features': ['sqrt', 'log2']
} 
-> 330,23 {'max_depth': 10, 'max_features': 'log2', 'n_estimators': 150}


# RF classification

## Two classes

In [18]:
from skopt import BayesSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# Kodek dla zmiennej kategorycznej 'City'
le = LabelEncoder()
all_data['City'] = le.fit_transform(all_data['City'])

X_train = all_data[(all_data.YEAR < 2019) & (all_data.Type == 'PM10')][['MONTH', 'City', 'Temperature', 'Wind', 'YEAR']]
X_test = all_data[(all_data.YEAR == 2019) & (all_data.Type == 'PM10')][['MONTH', 'City', 'Temperature', 'Wind', 'YEAR']]
y_train = all_data[(all_data.YEAR < 2019) & (all_data.Type == 'PM10')].Value_two_degree
y_test = all_data[(all_data.YEAR == 2019) & (all_data.Type == 'PM10')].Value_two_degree

# zdefiniuj zakresy hiperparametrów
param_space = {
    'n_estimators': (10, 1000),
    'max_depth': (1, 50),
    'min_samples_split': (2, 10),
    'min_samples_leaf': (1, 10),
}

model = RandomForestClassifier(random_state=42)

# zdefiniuj i przeprowadź przeszukiwanie bayesowskie
opt = BayesSearchCV(model, param_space, n_iter=50, random_state=42)
opt.fit(X_train, y_train)

# wybierz najlepszy model
best_model = opt.best_estimator_
print
# przewiduj na danych testowych
y_pred = best_model.predict(X_test)


KeyboardInterrupt: 

In [ ]:
opt.best_params_

In [28]:
print('Training data')
print(classification_report(y_train, best_model.predict(X_train)))
print(confusion_matrix(y_train, best_model.predict(X_train)))

print('Testing data')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Training data
              precision    recall  f1-score   support

          -1       0.81      0.53      0.64      1286
           1       0.90      0.97      0.93      5592

    accuracy                           0.89      6878
   macro avg       0.85      0.75      0.79      6878
weighted avg       0.88      0.89      0.88      6878

[[ 683  603]
 [ 163 5429]]
Testing data
              precision    recall  f1-score   support

          -1       0.60      0.36      0.45       292
           1       0.88      0.95      0.91      1432

    accuracy                           0.85      1724
   macro avg       0.74      0.66      0.68      1724
weighted avg       0.83      0.85      0.84      1724

[[ 106  186]
 [  70 1362]]


## Six classes

In [19]:
from skopt import BayesSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

# Kodek dla zmiennej kategorycznej 'City'
le = LabelEncoder()
all_data['City'] = le.fit_transform(all_data['City'])

X_train = all_data[(all_data.YEAR < 2019) & (all_data.Type == 'PM10')][['MONTH', 'City', 'Temperature', 'Wind', 'YEAR']]
X_test = all_data[(all_data.YEAR == 2019) & (all_data.Type == 'PM10')][['MONTH', 'City', 'Temperature', 'Wind', 'YEAR']]
y_train = all_data[(all_data.YEAR < 2019) & (all_data.Type == 'PM10')].Value_six_degree
y_test = all_data[(all_data.YEAR == 2019) & (all_data.Type == 'PM10')].Value_six_degree

# zdefiniuj zakresy hiperparametrów
param_space = {
    'n_estimators': (10, 1000),
    'max_depth': (1, 50),
    'min_samples_split': (8, 15),
    'min_samples_leaf': (8, 15),
}

model = RandomForestClassifier(random_state=42)

# zdefiniuj i przeprowadź przeszukiwanie bayesowskie
opt = BayesSearchCV(model, param_space, n_iter=50, random_state=42)
opt.fit(X_train, y_train)

# wybierz najlepszy model
best_model = opt.best_estimator_
print
# przewiduj na danych testowych
y_pred = best_model.predict(X_test)


In [20]:
opt.best_params_

OrderedDict([('max_depth', 44),
             ('min_samples_leaf', 15),
             ('min_samples_split', 14),
             ('n_estimators', 203)])

In [21]:
print('Training data')
print(classification_report(y_train, best_model.predict(X_train)))
print(confusion_matrix(y_train, best_model.predict(X_train)))

print('Testing data')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Training data
              precision    recall  f1-score   support

          -3       0.59      0.24      0.34        41
          -2       1.00      0.01      0.02       103
          -1       1.00      0.01      0.02       232
           1       0.47      0.21      0.29       884
           2       0.68      0.90      0.77      3776
           3       0.76      0.60      0.67      1842

    accuracy                           0.68      6878
   macro avg       0.75      0.33      0.35      6878
weighted avg       0.69      0.68      0.64      6878

[[  10    0    0   16   15    0]
 [   6    1    0   51   45    0]
 [   0    0    2   83  147    0]
 [   1    0    0  185  686   12]
 [   0    0    0   55 3383  338]
 [   0    0    0    6  724 1112]]
Testing data
              precision    recall  f1-score   support

          -3       0.00      0.00      0.00         5
          -2       0.00      0.00      0.00        20
          -1       0.00      0.00      0.00        52
           1  

C:\Users\kaami\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kaami\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kaami\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
